### ISSUE TITLE
Width on "diff" pages needs to be moar.

### ISSUE THREAD

**Issue by flavorjones** [buddhistpirate/widehub#1]
On diff pages (both unified and split view) the viewport is actually _smaller_ than the standard Github CSS. I'll attach a screenshot.

**Comment by flavorjones** [comment]
![screen shot 2014-11-12 at 12 28 39 pm](https://cloud.githubusercontent.com/assets/8207/5014993/dedf10c4-6a67-11e4-9014-9e1cb736fb6a.png)

**Comment by flavorjones** [comment]
Actually, I think it's only the "split view" that's smaller, not the "unified view".

**Comment by buddhistpirate** [comment]
Finally did it! 7f81a4473da180d68e18032a553f02b59b091f59
Also released that version to the chrome store!

**Comment by buddhistpirate** [comment]
Handle when the diff parameter is not present: 6c7eff442a53d06f4af05a9de37134bbcdbb4007

**Comment by flavorjones** [comment]
Woot! Thanks.
